# Generated by Django 2.2.16 on 2022-11-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.IntegerField(verbose_name='Код подтверждения'),
        ),
    ]
