# Generated by Django 2.2.16 on 2022-11-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221104_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.IntegerField(null=True, verbose_name='Код подтверждения'),
        ),
    ]
