# Generated by Django 2.2.16 on 2022-11-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(help_text='Год выпуска произведения', max_length=4, verbose_name='Год выпуска'),
        ),
    ]
