# Generated by Django 2.2.16 on 2022-11-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20221101_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Год выпуска произведения', verbose_name='Год выпуска'),
        ),
    ]
