# Generated by Django 2.2.16 on 2022-11-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_auto_20221103_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(related_name='titles', through='titles.GenreTitle', to='titles.Genre'),
        ),
    ]
