# Generated by Django 2.2.16 on 2022-11-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_auto_20221103_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Адрес категории в адресной строке', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(help_text='Адрес жанра в адресной строке', unique=True, verbose_name='Slug'),
        ),
    ]
