# Generated by Django 2.2.16 on 2022-11-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_auto_20221109_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
