# Generated by Django 2.2.16 on 2022-11-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0010_auto_20221109_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='genres',
            new_name='genre',
        ),
    ]
